theme: jekyll-theme-minimal
title: S2030C WebSite
description: Texte zu Sozialraum und Gemeinwesen, Commoning

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 1_start_2024-07-21.md
  - 2_organisation-gemeinwesen-2024.md
  - 4_es -geht-um-Menschen-2024-
  - 4_es -geht-um-Menschen-2024-
